![ITQ](img/logoitqv1.jpg)

## 0.1  01PAO 26-26, Estructura de datos + Pandas

![PYTHON](img/python_logo.png)

Kevin Yalama

[GitHub](https://github.com/kev1n-02/practica-machine.git)

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

## 1 Operaciones en pandas

#### Búsqueda

In [3]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  5  5  1
1  3  5  4

In [4]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [5]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0  False  False  False
1   True  False  False

In [6]:
 # Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
1
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False  False
1  False  False   True

[[False False False]
 [False False  True]]

numpy.ndarray

In [7]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

5

      A     B      C
0  True  True  False
1  True  True   True

#### Ordenación

In [8]:
from random import shuffle
rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices) # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
4   8   9  18   9
0   6   7  10   6
1   1   5  10  14
3  17  11  13   6
2  12  16   8   9

In [9]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   8   9  18   9
3  17  11  13   6
2  12  16   8   9
1   1   5  10  14
0   6   7  10   6

    D   A   C   B
4   8   9  18   9
0   6   7  10   6
1   1   5  10  14
3  17  11  13   6
2  12  16   8   9

In [10]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
4   8  18   9   9
0   6  10   6   7
1   1  10  14   5
3  17  13   6  11
2  12   8   9  16

In [11]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
1   1   5  10  14
0   6   7  10   6
4   8   9  18   9
3  17  11  13   6
2  12  16   8   9

In [12]:
 # ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    D   A   C   B
4   8   9  18   9
0   6   7  10   6
1   1   5  10  14
3  17  11  13   6
2  12  16   8   9

In [13]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
2  12  16   8   9
3  17  11  13   6
4   8   9  18   9
0   6   7  10   6
1   1   5  10  14

#### Ranking

- Construir un ranking de valores

In [14]:
display(frame)

    D   A   C   B
2  12  16   8   9
3  17  11  13   6
4   8   9  18   9
0   6   7  10   6
1   1   5  10  14

In [15]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
2  3.0  4.0  1.0  2.0
3  4.0  2.0  3.0  1.0
4  1.0  3.0  4.0  3.0
0  2.0  3.0  4.0  2.0
1  1.0  2.0  3.0  4.0

In [16]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

18
13
10
10
8

## 2 Operaciones

Operaciones matemáticas entre objetos

In [4]:
import numpy as np
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  76  91   9  78
1   4  29  83  46
2  23  31  40  43
3  92  37  55  14

    0   1   2   3
0  72  27  26   5
1  52  43  41  91
2  52  85  37  69
3  45  40  52  65

In [18]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0  145   97   81  143
1  133  102   72  150
2   10   50  120  133
3   29   31   32   63

In [19]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -17 -45 -45  13
1 -19 -84  60 -26
2   4  24 -64 -45
3   3  -1   8  29

In [20]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  81  71  63  65
1  76  93   6  88
2   3  13  92  89
3  13  16  12  17

    0   1   2
0  21   2   2
1   8  70  89
2   5  85  10

       0      1      2   3
0  102.0   73.0   65.0 NaN
1   84.0  163.0   95.0 NaN
2    8.0   98.0  102.0 NaN
3    NaN    NaN    NaN NaN

In [21]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0  102.0   73.0   65.0  65.0
1   84.0  163.0   95.0  88.0
2    8.0   98.0  102.0  89.0
3   13.0   16.0   12.0  17.0

Operadores aritméticos solo válidos en elementos aceptables

In [6]:
import pandas as pd
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
f=(frameA - frameD)

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrame

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

pandas se basa en NumPy, np operadores binarios y unarios son aceptables

# Operaciones Unarias y Binarias de NumPy

## Operaciones Unarias

| Tipo | Operación | Descripción |
|------|-----------|-------------|
| Unario | `abs` | Valor absoluto de cada elemento. |
| Unario | `sqrt` | Raíz cuadrada de cada elemento. |
| Unario | `exp` | Calcula \(e^x\), siendo **x** cada elemento. |
| Unario | `log`, `log10`, `log2` | Logaritmos en distintas bases de cada elemento. |
| Unario | `sign` | Retorna el signo de cada elemento (`-1` para negativo, `0` para cero y `1` para positivo). |
| Unario | `ceil` | Redondea cada elemento hacia arriba. |
| Unario | `floor` | Redondea cada elemento hacia abajo. |
| Unario | `isnan` | Indica si cada elemento es `NaN`. |
| Unario | `cos`, `sin`, `tan` | Operaciones trigonométricas sobre cada elemento. |
| Unario | `arccos`, `arcsin`, `arctan` | Inversas de las operaciones trigonométricas para cada elemento. |

---

## Operaciones Binarias

| Tipo | Operación | Descripción |
|------|-----------|-------------|
| Binario | `add` | Suma de dos arrays. |
| Binario | `subtract` | Resta de dos arrays. |
| Binario | `multiply` | Multiplicación de dos arrays. |
| Binario | `divide` | División de dos arrays. |
| Binario | `maximum`, `minimum` | Retorna el valor máximo o mínimo de cada pareja de elementos. |
| Binario | `equal`, `not_equal` | Compara si cada pareja de elementos es igual o diferente. |
| Binario | `greater`, `greater_equal`, `less`, `less_equal` | Compara cada pareja de elementos usando `>`, `>=`, `<` y `<=`, respectivamente. |

Aplicación de funciones a medida con lambda

In [ ]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por columna

In [ ]:
def max_min(x):
    return x.max() - x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

In [ ]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

## 3 Estadística descriptiva

- Análisis preliminar de los datos
- Para Series y DataFrame

# Operaciones Estadísticas en Pandas

| Operación | Descripción |
|-----------|-------------|
| `count` | Número de valores que no son `NaN`. |
| `describe` | Muestra un conjunto de estadísticas descriptivas del conjunto de datos. |
| `min`, `max` | Obtiene el valor mínimo y máximo de los datos. |
| `argmin`, `argmax` | Devuelve los índices posicionales del valor mínimo y máximo. |
| `idxmin`, `idxmax` | Devuelve las etiquetas (índices semánticos) del valor mínimo y máximo. |
| `sum` | Calcula la suma de los elementos. |
| `mean` | Calcula la media (promedio) de los elementos. |
| `median` | Calcula la mediana de los elementos. |
| `mad` | Calcula la desviación absoluta media respecto a la media. |
| `var` | Calcula la varianza de los elementos. |
| `std` | Calcula la desviación estándar de los elementos. |
| `cumsum` | Calcula la suma acumulada de los elementos. |
| `diff` | Calcula la diferencia entre elementos consecutivos. |

In [ ]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,34,11, 30],
"puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

In [ ]:
# operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

In [ ]:
frame.mean(numeric_only=True)

In [ ]:
frame.cumsum()

In [ ]:
frame.count(axis=1)

In [ ]:
print(frame['edad'].std())

In [ ]:
frame['edad'].idxmax()

In [ ]:
frame['puntos'].idxmin()

In [ ]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

In [ ]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [ ]:
display(frame)

#### 3.1 Agregaciones

In [ ]:
display(frame)
df = frame.groupby('genero').count()
display(df)

In [ ]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

In [ ]:
display(frame.groupby('genero').mean(numeric_only=True))

In [ ]:
display(frame.groupby('genero').max())

In [ ]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean','max']))

In [ ]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30
display(frame)
frame.groupby('genero').filter(media)

#### 3.2 Correlaciones
pandas incluye métodos para analizar correlaciones - Relación matemática entre dos variables
(-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación) - obj.corr(obj2) –
> medida de correlación entre los datos de ambos objetos -  https://blogs.oracle.com/ai-anddatascience/post/introduction-to-correlation

#### 3.2.1 Ejemplo Fuel efficiency

 https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [24]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
names = ['mpg', 'cilindros', 'desplazamiento','potencia',
'peso', 'aceleracion', 'año', 'origen', 'nombre'],
na_values='?', engine='c')

In [25]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
275,17.0,6,163.0,125.0,3140.0,13.6,78,2,volvo 264gl
39,14.0,8,400.0,175.0,4464.0,11.5,71,1,pontiac catalina brougham
42,12.0,8,383.0,180.0,4955.0,11.5,71,1,dodge monaco (sw)
254,20.2,6,200.0,85.0,2965.0,15.8,78,1,ford fairmont (auto)
369,34.0,4,112.0,88.0,2395.0,18.0,82,1,chevrolet cavalier 2-door

In [26]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [27]:
mpg_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 28.1 KB

#### 3.2.2 Correlaciones entre valores

In [28]:
mpg_data['mpg'].corr(mpg_data['peso']) # + mpg = - peso

np.float64(-0.8317409332443354)

In [29]:
mpg_data['peso'].corr(mpg_data['aceleracion']) # + peso = - aceleracion

np.float64(-0.41745731994039337)

#### 3.2.3 Correlaciones entre todos los valores

In [30]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [31]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [32]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [33]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [34]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [35]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax() 
#consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [36]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
positive_corr = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
np.fill_diagonal(positive_corr.values, 0)
display(positive_corr)
positive_corr.idxmax()

ValueError: underlying array is read-only

In [ ]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1,vmin=-1.0, vmax=1.0)

#### 3.3 Ejercicios

 - Ejercicios para practicar Pandas:
    
    https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb